### ISSUE TITLE
Currency amounts can suffer loss of precison when represented by Double

### ISSUE THREAD

**Issue by avrahamr** [wix/libpay#1]
Best practices dictate that currency amounts should not be represented by binary float point types to avoid loss of precision.

Please consider changing the API to either BigDecimal or to represent minor amount (cents) in int/long followed by the exponent. For instance:
{minorUnitsAmount: 199, exponent: 2, currency: 'USD'} means U$1.99

{minorUnitsAmount: 121, exponent: 0, currency: 'JPY'} means 121 Yens

**Comment by dleshem** [comment]
CurrencyAmount is used as a DTO, and for that purpose a Double is a good fit - I'm not aware of any payment gateway that uses a different data structure over-the-wire.

However, we can add a getter that returns the amount as BigDecimal, to be used for calculations.

**Comment by avrahamr** [comment]
We won't insist. Altough the payment gateways that we integrated use either Integer/Long for minor units. In any case, case closed.
