### ISSUE TITLE
Purpose / Documentation

### ISSUE THREAD

**Issue by vanthome** [wix/libpay#8]
Hi, I'm interested in a payment gateway for our micro services based Restore Commerce https://github.com/restorecommerce and that's why I would like to know whether this lib and all the modules are really intended to be/ become fully fledged open source? While I see that it is open source but there is no documentation at all for example. If so, we can contribute dockerization and more documentation.
BG

**Comment by dleshem** [comment]
Hi @vanthome - this library and related modules are indeed open source, and in active use by various Wix products. Documentation is lacking, unfortunately - it's on our roadmap, but has been pushed back so far.

Contributions of any kind are very welcome, feel free to email me at dannyl@wix.com.
